### ISSUE TITLE
cookies problem

### ISSUE THREAD

**Issue by windch** [zhu327/rss#1]
After the rss starting up, there is no cookies until several hours later, which will produce the following errors: 

    File "/var/lib/openshift/54fe6dc9e0b8cd2d250001cf/app-root/runtime/repo/diy/handlers/weixin.py", line 33, in get
      headers = random.choice(cookies)
    File "/var/lib/openshift/54fe6dc9e0b8cd2d250001cf/app-root/data/lib/python2.7/random.py", line 273, in choice
      return seq[int(self.random() * len(seq))]  # raises IndexError if seq is empty
TypeError: object of type 'NoneType' has no len()

Is there any way making the server functioning without waiting several hours?

Thanks.

**Comment by zhu327** [comment]
cookies为空吧，cookie会定时更新呀，每6个小时，定时任务在task.py里面，应该是cookie更新出问题了，导致没用cookie能用。

**Comment by windch** [comment]
请教这一行运行的时候，`get_cookies`会先运行一次，然后再每6小时运行一次。还是首次运行也要等到6小时后？多谢

    tornado.ioloop.PeriodicCallback(get_cookies, 6*60*60*1000).start()

**Comment by zhu327** [comment]
这个还真没仔细研究，应该是延时6小时才去运行，我以前是直接在后台手动导入了cookie的，所有没有你这个bug，如果需要立即执行的话，在`tornado.ioloop.IOLoop.instance().start()`后面加一行 `get_cookies()`

**Comment by windch** [comment]
试过加一行`get_cookies()`。好像没什么用。也可能因为我自己环境设置问题。
多谢。

**Comment by zhu327** [comment]
不行就放在前面试一下...记得不是很清楚。
