### ISSUE TITLE
微信公众号生成的RSS不起总用

### ISSUE THREAD

**Issue by qiwihui** [zhu327/rss#2]
微信公众号的文章生成的RSS不起作用，所有的公众号都是`404: Not Found`，可能是sogou在请求的链接中加入了一个AES生成的序列，而且这个序列是随时间变化的，以示例`openid=oIWsFt86NKeSGd_BQKp1GcDkYpv0`为例子：

之前请求的url为：
`http://weixin.sogou.com/gzhjs?cb=sogou.weixin.gzhcb&openid=oIWsFt86NKeSGd_BQKp1GcDkYpv0&page=1&t=1435331583433`

现在url为：
`http://weixin.sogou.com/gzhjs?cb=sogou.weixin.gzhcb&openid=oIWsFt86NKeSGd_BQKp1GcDkYpv0&eqs=tUsYo8OgE6twomWXaQdVku7NKxnk2wEmdNj6ZkctDPsSYcedigs324KsshDZJ5q7I%2FMZr&ekv=7&page=1&t=1435331583433`

增加的部分为:
`&eqs=tUsYo8OgE6twomWXaQdVku7NKxnk2wEmdNj6ZkctDPsSYcedigs324KsshDZJ5q7I%2FMZr&ekv=7`

从页面代码看来，`eqs`序列使用与`ekv`值对应的一个`key`和一个固定的`iv`生成的AES加密序列，请问这个序列要怎么解决呢？

**Comment by wlwr** [comment]
可以参考 https://github.com/wlwr/rss 破解方式

**Comment by qiwihui** [comment]
这个问题按照上面的方法解决了，在VPS上测试有效，参见 [Pull requests#3](https://github.com/zhu327/rss/pull/3).

**Comment by zhu327** [comment]
404是因为我屏蔽掉url了,访问量太大,导致即使cookie有效,也会有封ip的时候,像游戏技能
CD一样,过一段时间又好了,但是会造成openshift后台产生大量错误日志,上次就直接把磁盘占满了,不得已才屏蔽了url

**Comment by qiwihui** [comment]
我在VPS上用supervisor控制日志的输出大小为10M，在Openshift上应该也有类似的设置，这个文档：[Log Files: configuring-logging](https://developers.openshift.com/en/managing-log-files.html#configuring-logging)，10M大小是默认，所以可能是你的设置不太对。

**Comment by zhu327** [comment]
@qiwihui  @wlwr  重构了一下代码,又能访问啦,有个问题麻烦2位有空的时候看一下

我发现现在cookie里面的获取suv这个现在不是通过时间戳来生成的了,而是类似于SUID这样的字符串,找了一下sogou的js没发现哪里来生成这个suv,只在pb.nogz.js看到了getRandom这个函数,这里应该还能改进一下

**Comment by wlwr** [comment]
```
var SUV = 'SUV=' + ((new Date()).getTime())*1000+Math.round(Math.random()*1000);
```
我是这样生成的，还是基于时间戳，可以正常运行。

**Comment by zhu327** [comment]
重构搞了2天,擦,才用了几小时,就被办ip了,估计国外的ip会特别关照
