### ISSUE TITLE
 https://diy-devz.rhcloud.com/ 已经失效

### ISSUE THREAD

**Issue by lqsxianxu** [zhu327/rss#21]
您好，
电脑小白，看了您写的那个部署方法，有点晕啊 。
您部署的 https://diy-devz.rhcloud.com/    打不开呢

现在这个方法还能够提取微信公众号rss吗？
感谢

**Comment by zhu327** [comment]
已经不能用了

**Comment by lqsxianxu** [comment]
额，那还有其他方法吗？
提取自定义公众号rss的
