### ISSUE TITLE
AES.new 异常，key不满16位

### ISSUE THREAD

**Issue by chufuxi** [zhu327/rss#4]
_cipher_eqs（）
if len(h) > 5:
        n = h[:-5]
只补了一位

**Comment by zhu327** [comment]
不懂，这里的代码是别人提交pull request，然后我抄过来的

**Comment by chufuxi** [comment]
O(∩_∩)O，不知道这位同学后来有没有发现问题，我改成补满16位就ok了

**Comment by zhu327** [comment]
那你把修改提交过来吧

**Comment by chufuxi** [comment]
最好还是原作者来看下吧，我只是临时改了一下，不确定会有什么影响 ：）

**Comment by zhu327** [comment]
你可以看一下sogou的原来的js处理的过程，我看了一下，就是不足5位就用‘s’补满5位
