### ISSUE TITLE
tornado安装失败

### ISSUE THREAD

**Issue by ChuLiqiang** [zhu327/rss#5]
![error](https://cloud.githubusercontent.com/assets/2747722/8726799/f00afc78-2c0e-11e5-9667-4a8834d8415c.PNG)
![1](https://cloud.githubusercontent.com/assets/2747722/8749379/c8b62e0c-2cd3-11e5-9e58-553955508f5d.PNG)
![2](https://cloud.githubusercontent.com/assets/2747722/8749396/e317508c-2cd3-11e5-8ea1-d3b3a971b61d.PNG)

部署在Openshift diy tornado环境上，环境搭建参考:
http://bozpy.sinaapp.com/blog/29
按照教程出现上述安装错误。好象是权限问题，你碰到了吗?

**Comment by zhu327** [comment]
没有哦，我是ssh上去安装的

**Comment by ChuLiqiang** [comment]
怎么办？rch ssh上去装的。能帮忙建立个应用验证一下吗？

**Comment by ChuLiqiang** [comment]
能帮忙看看吗？我又上传了几张图。

**Comment by ChuLiqiang** [comment]
问题好象是 /var/lib/openshift/55a7a9f9e0b8cd42ae000195/.cache 没法在55a7a9f9e0b8cd42ae000195的APP目录下建立文件夹。你们怎么弄的？？？？

**Comment by ChuLiqiang** [comment]
按照下面的教程重新做了一遍成功了https://blog.openshift.com/enabling-python-27-on-a-paas-with-the-openshift-diy-app-type/

**Comment by ChuLiqiang** [comment]
PIP这样安装教程就能走通

Change into the OpenShift “tmp” directory:

cd $OPENSHIFT_TMP_DIR

Download and install setuptools:

wget http://pypi.python.org/packages/source/p/pip/pip-1.1.tar.gz

tar zxf pip-1.1.tar.gz

cd pip-1.1

Install:

$OPENSHIFT_DATA_DIR/bin/python setup.py install

**Comment by ChuLiqiang** [comment]
install ok.
